### PR TITLE
Use router infos for crumb generation to support resetNamespace

### PR DESCRIPTION
**Pull request by ivanvanderbyl**
_This PR is potentially a breaking change._

[Previously](https://github.com/poteto/ember-crumbly/blob/develop/addon/components/bread-crumbs.js#L37), using `resetNamespace` would break the crumb chain because we only checked the `currentRouteName` for tokens to generate crumbs from. The `currentRouteName` doesn't include anything before a `resetNamespace`. 

To fix this I've used the router's `handlerInfos` to build a list of all active route names, then removed any which weren't part of the `currentPath`.

While implementing this change it occurred to me that the current implementation is possibly incorrect, to explain this let's assume we have the following route paths active:

[`foo`, `foo.bar`, `foo.bar.baz`]

In the current implementation is would look for an `index` route at the start by attempting a lookup on `foo.index`, if it's implemented. So the lookup paths are: [`foo.index`, `foo.bar`, `foo.bar.baz`] ([see tests](https://github.com/poteto/ember-crumbly/blob/develop/tests/acceptance/integration-test.js#L148)). This behaviour is unexpected because `foo.index` isn't active, but `foo` is.

I believe the correct lookup should be: [`foo`, `foo.bar`, `foo.bar.baz.index`], because we're in the index route.

Was there a design decision around this that I've missed completely?

_This PR also includes the `isTail` and `isHead` functionality from #51_

### CODE REVIEW

**Comment by ivanvanderbyl** [comment]
I fixed those merge conflicts

**Comment by dguettler** [comment]
@ivanvanderbyl could you rebase this against `master`

**Comment by dguettler** [comment]
@ivanvanderbyl  closing this PR to avoid future confusion about branches. Can you please reopen against `master` - Thank you

**Comment by cbou** [comment]
This PR is quite old... Is resetNamespace supported by the plugin?

**Pull request closed without merging**
