### PR TITLE
Add isTail and isHead to breadcrumb data

### PR DESCRIPTION
**Pull request by ivanvanderbyl**
This allows for advanced customisations where you need to customise the first or last crumb. In my use case I need to make the last crumb a dropdown menu, similar to Google Drive.

### CODE REVIEW

**Comment by ivanvanderbyl** [comment]
@homu that should be fixed now

**Comment by ivanvanderbyl** [comment]
Ping @homu @poteto ?

**Comment by dguettler** [comment]
This looks good to me, @poteto any objections on this?

**Comment by poteto** [comment]
:shipit:

**Pull request merged**
