### PR TITLE
Multiple breadcrumbs functionality

### PR DESCRIPTION
**Pull request by alvinvogelzang**
As mentioned in https://github.com/poteto/ember-crumbly/issues/19 it would be nice to have a multiple breadcrumbs functionality. I created some custom functionality in my own application and maybe it's useful for others as well so I made this PR.

You can basically ad a `multipleBreadCrumbs` array to your route and add as many breadcrumbs you need. 

Example:

```
export default Ember.Route.extend({
  multipleBreadCrumbs: [],

  model(params) {
    return this.store.findRecord('car', params.car_id);
  },

  afterModel(model) {
    let multipleBreadCrumbs = [{
      title: 'Cars',
      linkable: true,
      path: 'cars.overview'
    },
    {
      title: model.get('name'),
      linkable: true
    }];

    set(this, 'multipleBreadCrumbs', multipleBreadCrumbs);
  }
});
```

### CODE REVIEW

**Comment by alvinvogelzang** [comment]
Sorry for the late response. Will take a look at it :-)

**Comment by dguettler** [comment]
@alvinvogelzang could you please rebase against `master`

**Comment by alvinvogelzang** [comment]
Sorry quite late. I'll try to fix it later this week

**Comment by alvinvogelzang** [comment]
@dguettler I rebased it against master

**Comment by dguettler** [comment]
Sorry looks like my last PR created some conflicts with this solution.
Overall I think this looks good.

From an API standpoint I'd probably go with `breadCrumbs` instead of `multipleBreadCrumbs` this would IMO fall better in line with `breadCrumb`

Also could you please add some tests around this functionality.

Thanks, Daniel

**Comment by knownasilya** [comment]
@alvinvogelzang ping on this last comment from @dguettler

**Pull request closed without merging**
