### PR TITLE
Specify linkClass on bread-crumbs component

### PR DESCRIPTION
**Pull request by andybluntish**
Implements #20.

### CODE REVIEW

**Comment by tsteuwer** [comment]
This is greatly needed. Everyone uses the standard dasherized class names, even ember itself is dasherized everything

**Comment by poteto** [comment]
Thanks for this! Could you please squash it down to a single commit?

**Comment by andybluntish** [comment]
No worries, all fixed now. Sorry about that :flushed:.

**Comment by poteto** [comment]
:+1:

**Pull request merged**
