### PR TITLE
Engines support

### PR DESCRIPTION
**Pull request by scottkidder**
Rebased @ascudder great work in #123 onto latest master and included @dguettler requested changes from #123

### CODE REVIEW

**Comment by dguettler** [comment]
I’ll push an updated version tomorrow morning once back at a computer.

**Comment by dguettler** [comment]
thanks @scottkidder for doing the rebase and refactor

**Comment by abhishek97** [comment]
@dguettler @poteto  Can you please publish a new version with engines support?
I am using this plugin(v3.0.1), but it breaks for engines.

**Comment by peyloride** [comment]
Hello is there any news about new release?

**Pull request merged**
