### PR TITLE
Make default last child as non-linkable

### PR DESCRIPTION
**Pull request by abhilashlr**
This PR contains updated test cases as well.

### CODE REVIEW

**Comment by topaxi** [comment]
I like this, any reasons this isn't merged yet?

**Comment by poteto** [comment]
You'll need to rebase this. Could you also please squash this down into 1 commit? Thanks!

**Comment by abhilashlr** [comment]
Yes sure @poteto.

**Comment by abhilashlr** [comment]
@poteto done!

**Pull request closed without merging**
